name: Go Quality Sub-Context
on:
  workflow_call:
jobs:
  validate-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Initialize Go Environment
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: '1.22'
      - name: Enforce Go Verifications
        run: go vet ./...
