name: Java Quality Sub-Context
on:
  workflow_call:
jobs:
  validate-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Initialize Java JDK
        uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Route Java Test Execution
        run: |
          if [ -f ./gradlew ]; then ./gradlew test; elif [ -f ./mvnw ]; then ./mvnw clean test; else echo "Skipping standalone build evaluation."; fi
