name: Rust Quality Sub-Context
on:
  workflow_call:
jobs:
  validate-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Initialize Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1
        with:
          components: clippy, rustfmt
      - name: Enforce Code Review Controls
        run: cargo clippy -- -D warnings
